# okareo config
project_name: okareo
builds:
  - binary: okareo
    id: okareo

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false  # This prevents the creation of directories
    files:
      - none*