# okareo config
project_name: okareo
builds:
  - binary: "okareo"
    id: okareo
    dir: .
    no_unique_dist_dir: true
    mod_timestamp: '{{ .CommitTimestamp }}'
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
    hooks:
      post: |
        chmod +x {{ .Path }}

archives:
  - format: tar.gz    # Changed from binary to tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false    # This ensures no folder inside the tar
    files:
      - none*

release:
  extra_files:
    - glob: README.md
    - glob: LICENSE