# okareo config
project_name: okareo
builds:
  - binary: "okareo"  # Simple name without OS/arch
    id: okareo
    dir: .
    no_unique_dist_dir: false  # Changed to true to ensure proper separation of builds
    mod_timestamp: '{{ .CommitTimestamp }}'
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
    hooks:
      post: |
        chmod +x {{ .Path }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - none*

release:
  extra_files:
    - glob: README.md
    - glob: LICENSE