name: CLI Evaluation 
api-key: ${OKAREO_API_KEY}
model-keys:
  -openai: ${OPENAI_API_KEY}
#language: "typescript"
run:
  flows:
#    file-pattern: '.*\.ts'
    configs:
#      - name: "Generation Config"
#        model-id: "a664de82-d9fe-482b-815f-8b007edb70d6"
#        scenario-id: "7cf8e6df-6023-47ed-b2eb-8d1ff8ed1c2f"
#        type: "NL_GENERATION"
#        openai-key: "${OPENAI_API_KEY}"
#        checks:
#          - uniqueness
#          - fluency

#      - name: "Classification Config"
#        model-id: "1c2298d8-0223-4b0a-bc88-1c67a4807b4f"
#        scenario-id: "733ab11a-cee5-49e4-b0f6-c2386752c9ac"
#        type: "MULTI_CLASS_CLASSIFICATION"
      
